package com.ssh.entity;
// Generated 2018-2-2 15:31:19 by Hibernate Tools 4.3.5.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AcctAuthority generated by hbm2java
 */
@Entity
@Table(name = "acct_authority", catalog = "sshdb")
public class AcctAuthority implements java.io.Serializable {

	private AcctAuthorityId id;

	public AcctAuthority() {
	}

	public AcctAuthority(AcctAuthorityId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({ @AttributeOverride(name = "id", column = @Column(name = "id", length = 36)),
			@AttributeOverride(name = "name", column = @Column(name = "name")) })
	public AcctAuthorityId getId() {
		return this.id;
	}

	public void setId(AcctAuthorityId id) {
		this.id = id;
	}

}
