package entity;
// Generated 2018-2-2 15:31:19 by Hibernate Tools 4.3.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AcctRole generated by hbm2java
 */
@Entity
@Table(name = "acct_role", catalog = "sshdb")
public class AcctRole implements java.io.Serializable {

	private String id;
	private String name;

	public AcctRole() {
	}

	public AcctRole(String id) {
		this.id = id;
	}

	public AcctRole(String id, String name) {
		this.id = id;
		this.name = name;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false, length = 36)
	public String getId() {
		return this.id;
	}

	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

}
